### ISSUE TITLE
Deleting your token doesn't actually hide it. 

### ISSUE THREAD

**Issue by lukekrikorian** [ambrosehayes5/smcc#24]
Hey there, just wanted to let you know that the discord token you deleted in [this commit](https://github.com/ambrosehayes5/smcc/commit/bf69011a6fccd355f9862553d2db67561bd63c12) isn't actually hidden, due to the way github and commits work. You pretty much have a few options if you want to keep it hidden. You can delete the repo and copy the code to a new one (without the token of course) or you can follow the instructions [here](https://help.github.com/articles/removing-sensitive-data-from-a-repository/).

It's a pretty easy mistake to make, I've done it a few times myself :) 

Good luck with this project! :)

**Comment by GenericError** [comment]
@lukekrikorian hey mate.

We regenerated the code with Discord and then set the new one in Heroku.

Thanks for the support!

**Comment by lukekrikorian** [comment]
Good to hear. :)
